# Soring, searching, and counting

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.11.2'

In [ ]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
np.sort(x, axis=1)

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames))

array([1, 2, 0])

Q3. Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])
np.argsort(x, axis=1)

array([[0, 1],
       [1, 0]])

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [13]:
x = np.random.permutation(10)
print(x)
print(np.partition(x, 5))

[8 0 6 5 9 1 2 7 3 4]
[1 3 2 4 0 5 6 7 8 9]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [12]:
x = np.random.permutation(10)
print(x)
print(np.partition(x, 3))

[3 1 7 2 5 8 4 6 0 9]
[0 1 2 3 4 5 8 6 7 9]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [14]:
x = np.random.permutation(10).reshape(2, 5)
print(x)
print(np.max(x, 1))
print(np.argmax(x, 1))
print(np.min(x, 1))
print(np.argmin(x, 1))

[[4 1 7 2 3]
 [9 8 0 5 6]]
[7 9]
[2 0]
[1 0]
[1 2]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [16]:
x = np.array([[np.nan, 4], [3, 2]])
print(np.nanmax(x, 1))
print(np.nanargmax(x, 1))
print(np.nanmin(x, 1))
print(np.nanargmin(x, 1))

[4. 3.]
[1 0]
[4. 2.]
[1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [17]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print(x[x > 2])
print(np.nonzero(x > 2))

[3 3 5]
(array([0, 1, 1]), array([2, 1, 2]))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [18]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x > 2)

array([2, 4, 5])

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [19]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x < 0, 0, x)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [20]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3])

## Counting

Q12. Get the number of nonzero elements in x.

In [21]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5